name: 'Setup PHP-SDK Action'
description: "Setup Windows build environment for PHP extensions"

inputs:
  version:
    description: "PHP version to build for"
    required: true
  arch:
    description: "The architecture to build for (x64 or x86)"
    required: true
  ts:
    description: "Thread-safety (nts or ts)"
    required: true
  deps:
    description: "List of dependency libraries"
    required: false
    default: '@()'
  devcmd:
    description: "Enable develeoper command prompt"
    required: false
    default: 'true'

outputs:
  toolset:
    description: "The required toolset version"
    value: ${{steps.vars.outputs.toolset}}
  prefix:
    description: "The prefix of the PHP installation"
    value: ${{steps.vars.outputs.prefix}}
  vs:
    description: "The Visual Studio version"
    value: ${{steps.vars.outputs.vs}}
  file_tag:
    description: "A tag to use in output file names"
    value: ${{steps.vars.outputs.file_tag}}

runs:
  using: "composite"
  steps:

    - name: "determine toolset vars"
      id: "vars"
      shell: powershell
      run: ${{github.action_path}}/scripts/vars.ps1 -version ${{inputs.version}} -ts ${{inputs.ts}} -arch ${{inputs.arch}}

    - name: "checkout PHP SDK"
      id: "sdk"
      uses: actions/checkout@v3
      with:
        repository: php/php-sdk-binary-tools
        path: php-sdk

    - name: "download PHP"
      id: "php"
      shell: bash
      run: |
        curl -LO ${{steps.vars.outputs.baseurl}}/${{steps.vars.outputs.phpzip}}
        7z x ${{steps.vars.outputs.phpzip}} -o./php-bin
#        ls ./php-bin

    - name: "download development pack"
      id: "devpack"
      shell: bash
      run: |
        curl -LO ${{steps.vars.outputs.baseurl}}/${{steps.vars.outputs.dpzip}}
        7z x ${{steps.vars.outputs.dpzip}} -o.
        mv ./${{steps.vars.outputs.dpdir}} ./php-dev
#        ls ./php-dev

    - name: "fetch additional php-sdk dependencies"
      id: "deps"
      shell: powershell
      run: ${{github.action_path}}/scripts/deps.ps1 -version ${{inputs.version}} -vs ${{steps.vars.outputs.vs}} -arch ${{inputs.arch}} -deps ${{inputs.deps}}

    - name: "Enable Developer Command Prompt"
      id: "devcmd"
      if: ${{inputs.devcmd == 'true'}}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{inputs.arch}}
        toolset: ${{steps.vars.outputs.toolset}}
