name: "Setup PHP-SDK Action"
description: "Setup Windows build environment for PHP extensions"

inputs:
  version:
    description: "PHP version to build for"
    required: true
  arch:
    description: "The architecture to build for (x64 or x86)"
    required: true
  ts:
    description: "Thread-safety (nts or ts)"
    required: true
  deps:
    description: "List of dependency libraries"
    required: false
    default: '@()'
  devcmd:
    description: "Enable develeoper command prompt"
    required: false
    default: 'true'
  sdkref:
    description: "The tag or SHA of the desired version of php/php-sdk-binary-tools"
    required: false
    default: '775cf0dbfafd8f563451f94d0d0a2a5d8a7ec623'

outputs:
  toolset:
    description: "The required toolset version"
    value: ${{steps.vars.outputs.toolset}}
  prefix:
    description: "The prefix of the PHP installation"
    value: ${{steps.vars.outputs.prefix}}
  vs:
    description: "The Visual Studio version"
    value: ${{steps.vars.outputs.vs}}
  buildpath:
    description: "The build output path"
    value: ${{steps.vars.outputs.buildpath}}
  file_tag:
    description: "A tag to use in output file names"
    value: ${{steps.vars.outputs.file_tag}}

runs:
  using: "composite"
  steps:

    - name: "determine toolset vars"
      id: "vars"
      shell: powershell
      run: ${{github.action_path}}/scripts/vars.ps1 -version ${{inputs.version}} -ts ${{inputs.ts}} -arch ${{inputs.arch}}

    - name: "download PHP + devpack"
      id: "php-dl"
      uses: codemasher/php-devpack-setup-win@main
      with:
        phpversion: ${{steps.vars.outputs.phpversion}}
        tspart: ${{steps.vars.outputs.tspart}}
        vs: ${{steps.vars.outputs.vs}}
        arch: ${{inputs.arch}}
        baseurl: ${{steps.vars.outputs.baseurl}}

    - name: "Setup SDK cache"
      id: "sdk-cache"
      uses: actions/cache@v3
      with:
        path: php-sdk
        key: php-sdk-binary-tools-${{inputs.sdkref}}

    - name: "checkout PHP SDK"
      id: "sdk"
      if: steps.sdk-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: php/php-sdk-binary-tools
        path: php-sdk
        ref: ${{inputs.sdkref}}

    # we rename the tar.exe that's included with the sdk because it breaks actions/cache
    # there's newer/different one in C:\Windows\System32\tar.exe which is usually being used
    - name: "check paths"
      id: "paths"
      shell: powershell
      run: |
        Get-ChildItem -Path .\php-bin
        Get-ChildItem -Path .\php-dev
        Get-ChildItem -Path .\php-sdk
        try{
            Rename-Item -Path "${{steps.vars.outputs.sdkusrbin}}\tar.exe" -NewName "tar.old"
        }
        catch{}

    - name: "fetch additional php-sdk dependencies"
      id: "deps"
      shell: powershell
      run: ${{github.action_path}}/scripts/deps.ps1 -version ${{inputs.version}} -vs ${{steps.vars.outputs.vs}} -arch ${{inputs.arch}} -deps ${{inputs.deps}}

    - name: "Enable Developer Command Prompt"
      id: "devcmd"
      if: ${{inputs.devcmd == 'true'}}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{inputs.arch}}
        toolset: ${{steps.vars.outputs.toolset}}
